server:
  port: 8081

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost/location?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: 'update'
      show-sql: true
      format_sql: true
      use_sql_comments: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL8Dialect'
  zipkin:
    base-url: http://localhost:9411
#   rabbitmq:
#     host: localhost
#     port: 5672
#     username: guest
#     password: guest
  boot:
    message: 'Hello, location-service updated 22.12.2022'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    
# management:
#   endpoints:
#     web:
#       exposure:
#         include: '*'
